spring.config.import=optional:secrets.properties
spring.application.name=springboot-1
jwt.expiration=3600000
#app.firebase-configuration.file=caroo-wash-notificaton-firebase-adminsdk-fbsvc-a4106493f9.json

#logging.level.org.springframework=DEBUG